/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ItemEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import model.Contato;
import model.Criptografia;
import model.ServicoContatoImpl;

/**
 *
 * @author fabriciogmc
 */
public class TelaListagemBusca extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form TelaListagem
	 * 
	 * @throws IOException
	 */
	public static List<Contato> busca;
	public static String[] user;
	public Contato contato;
	public String nomeUsuario;
	public int index;
	Criptografia c = new Criptografia();

	public TelaListagemBusca(String[] user, List<Contato> busca) throws IOException {
		TelaListagemBusca.user = user;
		TelaListagemBusca.busca = busca;
		initComponents();
		nomeUsuario = "";
		for (String s : user) {
			nomeUsuario = nomeUsuario + s;
		}
		if (busca == null) busca = new ArrayList<Contato>();
		else {
			for (Contato contato : busca) {
				this.list1.add(contato.dadosFormatados());
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * 
	 * @throws IOException
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() throws IOException {
		jLabel1 = new javax.swing.JLabel();
		list1 = new java.awt.List();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

		jLabel1.setText("Contatos existentes na agenda:");

		list1.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				if (evt.getStateChange() == ItemEvent.SELECTED) {
					index = list1.getSelectedIndex();
					contato = busca.get(index);
				}
			}
		});

		jButton1.setText("Editar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					new EditarCadastro(user, contato.getNomeContato());
					EditarCadastro.main(user);
					dispose();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		});

		jButton2.setText("Excluir");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				String arq = "data_u" + c.cripto(nomeUsuario, 3) + ".txt";
				ServicoContatoImpl servCont = new ServicoContatoImpl(arq);
				servCont.removerContato(contato);
				try {
					new TelaListagem(user);
					TelaListagem.main(user);
					dispose();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(33, 33, 33)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addComponent(jButton1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton2))
								.addComponent(jLabel1).addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 306,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(41, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
								.addGap(22, 22, 22)
								.addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 218,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(23, 23, 23)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButton1).addComponent(jButton2))
								.addContainerGap(32, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents


	public static void main(String[] user) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaListagemBusca.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaListagemBusca.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaListagemBusca.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaListagemBusca.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new TelaListagemBusca(user, busca).setVisible(true);
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private java.awt.List list1;
	// End of variables declaration//GEN-END:variables
}
